version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      #- frontend-node-modules:/workspaces/sf-detailing/frontend/node_modules

    env_file:
      - ../.env

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use separate network settings to enable port forwarding
    networks:
      - app-network
    
    depends_on:
      - db

    ports:
      - "8001:8001"  # Django backend
      - "3000:3000"  # Next.js frontend

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    networks:
      - app-network
    ports:
      - "5433:5432"  # PostgreSQL

networks:
  app-network:

volumes:
  postgres-data:
  frontend-node-modules: