# Generated by Django 5.1.6 on 2025-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=250)),
                ("phone_number", models.CharField(max_length=25)),
                ("people", models.PositiveIntegerField(default=1)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("interior", "Interior"),
                            ("exterior", "Exterior"),
                            ("interior + exterior", "Interior + Exterior"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[("car", "Car"), ("suv", "SUV"), ("truck", "Truck")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
