# Generated by Django 5.1.6 on 2025-02-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="people",
        ),
    ]
