# Generated by Django 5.1.6 on 2025-03-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_booking_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["price"],
            },
        ),
    ]
