# Generated by Django 5.1.6 on 2025-03-04 01:59

from django.db import migrations

def standardize_package_names(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    
    # Standardize "interior + exterior" to "interior_exterior" for consistency
    Booking.objects.filter(package="interior + exterior").update(package="interior_exterior")

def reverse_func(apps, schema_editor):
    # Reverse operation if needed
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.filter(package="interior_exterior").update(package="interior + exterior")

class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0004_populate_package_data'),  # Update with actual migration number
    ]
    
    operations = [
        migrations.RunPython(standardize_package_names, reverse_func),
    ]