# Generated by Django 5.1.6 on 2025-03-04 02:04

from django.db import migrations

def link_bookings_to_packages(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    Package = apps.get_model('booking', 'Package')
    
    # Create a mapping of package names to Package objects
    package_map = {package.name: package for package in Package.objects.all()}
    
    # Update each booking to link to the corresponding package
    for booking in Booking.objects.all():
        if booking.package in package_map:
            booking.package_fk = package_map[booking.package]
            booking.save()
        else:
            print(f"Warning: No package found for '{booking.package}'")

def reverse_func(apps, schema_editor):
    # Optional reverse migration
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.update(package_fk=None)

class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0006_add_package_fk_field'),  # Update with actual migration number
    ]
    
    operations = [
        migrations.RunPython(link_bookings_to_packages, reverse_func),
    ]
