# Generated by Django 5.1.6 on 2025-03-04 02:06

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0007_link_bookings_to_packages'),  # Update with actual migration number
    ]
    
    operations = [
        # Remove the old CharFied
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        # Rename the ForeignKey field to 'package'
        migrations.RenameField(
            model_name='booking',
            old_name='package_fk',
            new_name='package',
        ),
    ]
