# Generated by Django 5.1.7 on 2025-04-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_create_initial_addons"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePackagePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "Car"), ("suv", "SUV"), ("truck", "Truck")],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_prices",
                        to="booking.package",
                    ),
                ),
            ],
            options={
                "ordering": ["package", "vehicle_type"],
                "unique_together": {("package", "vehicle_type")},
            },
        ),
    ]
